### ISSUE TITLE
Low resolution mesh

### ISSUE THREAD

**Issue by antithing** [AyoubKhammassi/BakedSDF2FBX#1]
Hi, I am using this code (and the UE plugin) with the example BakedSDF 'bicycle' dataset.
The mesh in UE is low resolution (eg, the bicycle is missing all the spokes) and the bounding sphere is very small, cutting off all the trees.

Questions:

1. Can I adjust the resolution somehow to keep all the fine detail?
2. Can I adjust the bounding sphere?

Thanks!

**Comment by thegenerativegeneration** [comment]
1. You cannot, as it does not seem like any detail was cut from the original file. If you check the original BakedSDF, the spokes are missing there too.
2. The sphere you see also originates in the original model file. The original paper implements the baked representation so that parts that are close to the center of the scene are represented with more Gaussian lobes than further away parts: "we use three spherical Gaussian lobes in the central regions (∥x∥ ≤ 1) and one lobe in the periphery". The author of this conversion script decided to cut away the parts of the baked model outside of the central region by checking how many lobes each vertex has. You can take out that part of the code and it will export the whole scene.

The parts of the scene that have three lobes vs one render differently which is also apparent in the official WebGL demo. I think the specular lighting of BakedSDF may generally be a little flawed.

**Comment by antithing** [comment]
Thanks for clarifying!
